### PR TITLE
CouchbaseBucket::query return now a CouchbaseResult which implements Iterator

### PR DESCRIPTION
**Pull request by syrm**
Hello,

This feature change the behavior of query to return an Iterator, that a more nice way to return the result and allow code like that : 

``` PHP
foreach ($db->query(CouchbaseN1qlQuery::fromString('SELECT * FROM `beer-sample`')) as $document) {
        var_dump($document);
}
```

### CODE REVIEW

**Comment by JordyMoos** [comment]
This would change backward compatibility.
You can make your own service wrapper around this library to have the result as an iterator right

**Comment by syrm** [comment]
Yes but that should be the default behavior.

**Comment by syrm** [comment]
I can change to this and add Countable interface yes

**Comment by syrm** [comment]
I added Countable interface

**Comment by SimonSimCity** [comment]
@oxman, I guess it's confusing if you add a countable interface and let that one return the full amount of items in that list. I do neither know if the full amount of this query or the amount of items returned is expected by the user. What do you guess?

I expect a collection to return the amount of items it has if I count it. Would yours? I guess when adding a limit, yours wouldn't return the amount of items returned.

**Comment by syrm** [comment]
Even if i wouldn't return the full amount of data, the C driver does it.
When the C driver would make iteration on the fly like a Mysql driver, CouchbaseResult will use it and no change will be needed.

And when you add a limit, you want the total number of items for your query (so with the limit).

**Comment by SimonSimCity** [comment]
@oxman yea, but that's not the case if we would take that code you wrote.

Please count the rows for the implementation of the `Countable` interface and return the full amount of rows in an extra parameter or method call.

You could decide to internally use the limit and query the next set if the user didn't add a limit - then your implementation would be correct, but that needs a lot more work.

**Comment by syrm** [comment]
Is it ok for you with this sample ?
https://gist.github.com/oxman/c0023e0bda77b812bdec

**Comment by SimonSimCity** [comment]
@oxman Looks good - but I have to admit, that I never tried out the n1ql feature. I was thinking about usual view-queries. Maybe the client returns other additional parameters, that are now inaccessible, when using n1ql ...

**Comment by syrm** [comment]
Well in view queries you can limit the result set with many options, like startkey, endkey, then the behavior is like N1QL with LIMIT.

**Comment by syrm** [comment]
@JordyMoos about backward compatibility, semver is designed for that.

**Comment by brett19** [comment]
We do not currently have plans in our roadmap to support streaming of results from Couchbase's querying API's.  Additionally, because of the nature of streaming, implementing Countable would not be possible if we did.

**Pull request closed without merging**
